function tans_simnibs(Subdir,OutDir,HeadModelDir,SearchGridCoords,CoilModel,AngleResolution,nThreads,Paths)
% cjl; cjl2007@med.cornell.edu;

% Inputs
% "Subdir": The path to the subject's folder.
% "HeadModelDir": The path to the head model folder.
% "OutDir": The path to the output folder.
% "SearchGridCoords": A nPositions X 3 array of coordinates corresponding to points on the scalp where we want to place the coil center.
% "AngleResolution": Inter angle resolution used in the search grid (e.g., 30).  
% "nThreads": Number of workers for parpool. 
% "CoilModel": 

% Notes: the script assumes HCP-like directory structures for 
% things like finding the surface files for volume-to-surface mapping. 

% define some directories;
addpath(genpath(Paths{1})); % define the path to SimNibs software
addpath(genpath(Paths{2})); % define the path to the folder containing "ft_read_cifti" / "gifti" functions

rng(44); % for reproducibility;
warning ('off','all'); % annoying warnings;

% infer the subject name;
str = strsplit(Subdir,'/');
Subject = str{end};

% define a bunch of files for volume-to-surface mapping;
PIAL_32k{1} = [Subdir '/anat/T1w/fsaverage_LR32k/' Subject '.L.pial.32k_fs_LR.surf.gii']; % pial surface (LH) 32k mesh
PIAL_32k{2} = [Subdir '/anat/T1w/fsaverage_LR32k/' Subject '.R.pial.32k_fs_LR.surf.gii']; % pial surface (RH) 32k mesh
WHITE_32k{1} = [Subdir '/anat/T1w/fsaverage_LR32k/' Subject '.L.white.32k_fs_LR.surf.gii']; % white surface (LH) 32k mesh
WHITE_32k{2} = [Subdir '/anat/T1w/fsaverage_LR32k/' Subject '.R.white.32k_fs_LR.surf.gii']; % white surface (RH) 32k mesh
MIDTHICK_32k{1} = [Subdir '/anat/T1w/fsaverage_LR32k/' Subject '.L.midthickness.32k_fs_LR.surf.gii']; % midthickness surface (LH) 32k mesh
MIDTHICK_32k{2} = [Subdir '/anat/T1w/fsaverage_LR32k/' Subject '.R.midthickness.32k_fs_LR.surf.gii']; % midthickness surface (RH) 32k mesh
ROI_32k{1} = [Subdir '/anat/MNINonLinear/fsaverage_LR32k/' Subject '.L.atlasroi.32k_fs_LR.shape.gii']; % medial wall mask (LH)
ROI_32k{2} = [Subdir '/anat/MNINonLinear/fsaverage_LR32k/' Subject '.R.atlasroi.32k_fs_LR.shape.gii']; % medial wall mask (RH)
SKIN = gifti([HeadModelDir '/m2m_' Subject '/Skin.surf.gii']); % skin mesh generated by "tans_headmodels.m"

%% loop through all the coil positions

% this is where we will store all the cifti files;
system(['mkdir -p ' OutDir '/SearchGrid/']);

% define a parpool;
pool = parpool('local',nThreads);

% sweep the search space;
parfor i = 1:size(SearchGridCoords,1)
    
    try % note: sometimes the scalp position is weird and the simulation will fail. 
        % So we have a try/catch here to prevent the whole thing from failing.
    
    % Initialize a session
    s = sim_struct('SESSION');
    
    % Name of head mesh
    s.fnamehead = [HeadModelDir '/' Subject '.msh'];
    
    % Output folder
    s.pathfem = [OutDir '/SearchGrid/Simulation_' sprintf('%05d',i) '/'];
    
    % Initialize a list of TMS simulations
    s.poslist{1} = sim_struct('TMSLIST');
    
    % specify the coil model;
    s.poslist{1}.fnamecoil = CoilModel;
    
    % generate an approximate circle around the center position (this is a bit crude but works fine); 
    D = pdist2(SKIN.vertices,[SearchGridCoords(i,1), SearchGridCoords(i,2), SearchGridCoords(i,3)]);
    A = find(D < 19); % inner diameter;
    B = find(D < 20); % outer diameter;
    Circle = SKIN.vertices(B(~ismember(B,A)),:); % find the difference;
    
    % cluster 3d coordinates;
    [~,yDirs] = kmeans(Circle,round(360 / AngleResolution));
    
    % sort coordinates in a radial fashion;
    [yDirs] = SortCircleCoords(yDirs); % 

    % sweep a range of 
    % coil orientations;
    for ii = 1:length(yDirs)
    
    % specify & save coil position;
    s.poslist{1}.pos(ii).centre = [SearchGridCoords(i,1), SearchGridCoords(i,2), SearchGridCoords(i,3)];
    s.poslist{1}.pos(ii).pos_ydir = [yDirs(ii,1), yDirs(ii,2), yDirs(ii,3)];

    end
    
    % write to volume;
    s.map_to_vol = true;
    s.fields = 'e'; % normE only;
    
    % run the
    % simulation;
    run_simnibs(s);
    
    % merge all the volumes into a single 4D file;
    system(['rm ' OutDir '/SearchGrid/Simulation_' sprintf('%05d',i) '/subject_volumes/normE*']); % 
    system(['fslmerge -t ' OutDir '/SearchGrid/Simulation_' sprintf('%05d',i) '/subject_volumes/normE.nii.gz ' OutDir '/SearchGrid/Simulation_' sprintf('%05d',i) '/subject_volumes/*normE.nii.gz']);
    
    % map concatenated volume to the 32k surface;
    system(['wb_command -volume-to-surface-mapping ' OutDir '/SearchGrid/Simulation_' sprintf('%05d',i) '/subject_volumes/normE.nii.gz  ' MIDTHICK_32k{1} ' ' OutDir '/SearchGrid/Simulation_' sprintf('%05d',i) '/subject_volumes/normE.L.32k_fs_LR.shape.gii -ribbon-constrained ' WHITE_32k{1} ' ' PIAL_32k{1} ' -interpolate ENCLOSING_VOXEL']);
    system(['wb_command -volume-to-surface-mapping ' OutDir '/SearchGrid/Simulation_' sprintf('%05d',i) '/subject_volumes/normE.nii.gz  ' MIDTHICK_32k{2} ' ' OutDir '/SearchGrid/Simulation_' sprintf('%05d',i) '/subject_volumes/normE.R.32k_fs_LR.shape.gii -ribbon-constrained ' WHITE_32k{2} ' ' PIAL_32k{2} ' -interpolate ENCLOSING_VOXEL']);
    system(['wb_command -metric-mask ' OutDir '/SearchGrid/Simulation_' sprintf('%05d',i) '/subject_volumes/normE.L.32k_fs_LR.shape.gii ' ROI_32k{1} ' ' OutDir '/SearchGrid/Simulation_' sprintf('%05d',i) '/subject_volumes/normE.L.32k_fs_LR.shape.gii']); 
    system(['wb_command -metric-mask ' OutDir '/SearchGrid/Simulation_' sprintf('%05d',i) '/subject_volumes/normE.R.32k_fs_LR.shape.gii ' ROI_32k{2} ' ' OutDir '/SearchGrid/Simulation_' sprintf('%05d',i) '/subject_volumes/normE.R.32k_fs_LR.shape.gii']);
    system(['wb_command -cifti-create-dense-timeseries ' OutDir '/SearchGrid/Simulation_' sprintf('%05d',i) '/subject_volumes/normE.dtseries.nii -left-metric ' OutDir '/SearchGrid/Simulation_' sprintf('%05d',i) '/subject_volumes/normE.L.32k_fs_LR.shape.gii -roi-left ' ROI_32k{1} ' -right-metric ' OutDir '/SearchGrid/Simulation_' sprintf('%05d',i) '/subject_volumes/normE.R.32k_fs_LR.shape.gii -roi-right ' ROI_32k{2}]);
    system(['mv ' OutDir '/SearchGrid/Simulation_' sprintf('%05d',i) '/subject_volumes/normE.dtseries.nii ' OutDir '/SearchGrid/normE_' sprintf('%05d',i) '.dtseries.nii']);
    system(['mv ' OutDir '/SearchGrid/Simulation_' sprintf('%05d',i) '/*.log ' OutDir '/SearchGrid/Simulation_' sprintf('%05d',i) '.log']);

    % remove some large intermediate files to save disk space;
    system(['rm -rf ' OutDir '/SearchGrid/Simulation_' sprintf('%05d',i) '/']);
  
    catch
    end
    
end

% delete the
% parpool;
delete(pool);

end

% sub-functions
function [Output] = SortCircleCoords(Coords)
% cjl; purpose: take a set of 3d coordinates 
% and order them in a radial fashion;

% preallocate;
Output = zeros(size(Coords));

% preallocate;
Used = [];
Idx = 1;

% sweep the coordinates;
for i = 1:size(Coords,1)
    D = pdist2(Coords(Idx,:),Coords);
    D(Used) = nan;
    Idx = find(D==min(nonzeros(D)));
    Idx = Idx(1); % in case there is more than one;
    Output(i,:) = Coords(Idx,:);
    Used = [Used Idx];
end

end



