function tans_optimize(Subdir,HeadModelDir,OutDir,Target,Thresholds,Sigma,ErrorTolerance,CoilModel,Paths)
% cjl; cjl2007@med.cornell.edu;
%
% Inputs
% "Subdir": The path to the subject's folder.
% "HeadModelDir": The path to the head model folder.
% "OutDir": The path to the output folder.
% "Target": A vertex (59412) x 1 array (O == non-target vertices, and 1 == target vertices).
% "Thresholds": A vector of percentiles used for operationalizing the E-field hotspot, such as linspace(99.9,99,10).
% "Sigma": Smoothing kernel size (sigma = 0.85 seems to work well).
% "ErrorTolerance": Coil center positioning uncertainity (in mm). Optimal coil placement is defined as the position that maximizes the on target value on average within this distance. 
% "CoilModel": 

% Notes: the script assumes HCP-like directory structures for 
% things like finding the surface files for volume-to-surface mapping. 

% define some directories;
addpath(genpath(Paths{1})); % define the path to SimNibs software
addpath(genpath(Paths{2})); % define the path to the folder containing "ft_read_cifti" / "gifti" functions

rng(44); % for reproducibility;
warning ('off','all'); % annoying warnings;

% infer the subject name;
str = strsplit(Subdir,'/');
Subject = str{end};

% define a bunch of files for volume-to-surface mapping;
PIAL_32k{1} = [Subdir '/anat/T1w/fsaverage_LR32k/' Subject '.L.pial.32k_fs_LR.surf.gii']; % pial surface (LH) 32k mesh
PIAL_32k{2} = [Subdir '/anat/T1w/fsaverage_LR32k/' Subject '.R.pial.32k_fs_LR.surf.gii']; % pial surface (RH) 32k mesh
WHITE_32k{1} = [Subdir '/anat/T1w/fsaverage_LR32k/' Subject '.L.white.32k_fs_LR.surf.gii']; % white surface (LH) 32k mesh
WHITE_32k{2} = [Subdir '/anat/T1w/fsaverage_LR32k/' Subject '.R.white.32k_fs_LR.surf.gii']; % white surface (RH) 32k mesh
MIDTHICK_32k{1} = [Subdir '/anat/T1w/fsaverage_LR32k/' Subject '.L.midthickness.32k_fs_LR.surf.gii']; % midthickness surface (LH) 32k mesh
MIDTHICK_32k{2} = [Subdir '/anat/T1w/fsaverage_LR32k/' Subject '.R.midthickness.32k_fs_LR.surf.gii']; % midthickness surface (RH) 32k mesh
ROI_32k{1} = [Subdir '/anat/MNINonLinear/fsaverage_LR32k/' Subject '.L.atlasroi.32k_fs_LR.shape.gii']; % medial wall mask (LH)
ROI_32k{2} = [Subdir '/anat/MNINonLinear/fsaverage_LR32k/' Subject '.R.atlasroi.32k_fs_LR.shape.gii']; % medial wall mask (RH)
VA = ft_read_cifti_mod([Subdir '/anat/T1w/fsaverage_LR32k/' Subject '.midthickness_va.32k_fs_LR.dscalar.nii']); % surface area occupied by each vertex;
SKIN = gifti([HeadModelDir '/m2m_' Subject '/Skin.surf.gii']); % skin mesh generated by "tans_headmodels.m"

%% evaluate E-fields associated with all the coil placements;

% load the previously generated metric file;
G = gifti([OutDir '/SearchGrid/SubSampledSearchGrid.shape.gii']); 
SearchGridVertices = find(G.cdata~=0); % 

% count the number of files (note: some attempts will have failed,
% for whatever reason, so we cant assume that file X is simulation X;
files = dir([OutDir '/SearchGrid/normE_*.dtseries.nii']);

% read the first file & count how many orientations were attempted
NormE = ft_read_cifti_mod([OutDir '/SearchGrid/' files(1).name]);
nCols = size(NormE.data,2);

% preallocate;
OnTarget = zeros(length(SearchGridVertices),...
nCols,length(Thresholds)); % "OnTaget" variable (% of E-field hotspot that contains in the ROI);

% sweep the search space;
for i = 1:length(files)
   
    % read in the CIFTI file;
    NormE = ft_read_cifti_mod([OutDir...
    '/SearchGrid/' files(i).name]);
    
    % make sure we have the correct point in the space grid;
    tmp = strsplit(files(i).name,{'_','.'}); % note: sometimes a given point in the search grid will fail;
    idx = str2double(tmp{2});
    
    % sweep the coil orientations;
    for ii = 1:size(NormE.data,2)
        
        % sweep all of the thresholds;
        for iii = 1:length(Thresholds)
            
            HotSpot = NormE.data(1:59412,ii) > prctile(NormE.data(1:59412,ii),Thresholds(iii)); % this is the hotspot
            OnTarget(idx,ii,iii) = sum(VA.data(HotSpot&Target==1)) / sum(VA.data(HotSpot));
            
        end
        
    end

    % clear 
    % variable
    clear NormE
    
end

% save some variables;
mkdir([OutDir '/Optimize']); % make the dir.;
save([OutDir '/Optimize/CoilCenter_OnTarget'],'OnTarget');

% average accross the e-field thresholds;
AvgOnTarget = mean(OnTarget,3); % on-target;

% create a template metric file;
system(['wb_command -volume-to-surface-mapping ' HeadModelDir '/m2m_' Subject '/skin.nii.gz '...
HeadModelDir '/m2m_' Subject '/Skin.surf.gii ' OutDir '/Optimize/CoilCenter_OnTarget.shape.gii -trilinear']); % 

% read in the template metric file;
G = gifti([OutDir '/Optimize/CoilCenter_OnTarget.shape.gii']);
G.cdata = zeros(size(G.cdata)); % blank slate;

% quality criteria (% hotspot on target)
G.cdata(SearchGridVertices) = max(AvgOnTarget,[],2); % average across orientations, for now.
save(G,[OutDir '/Optimize/CoilCenter_OnTarget.shape.gii']); % write out the on-target metric file;
system(['wb_command -metric-smoothing ' HeadModelDir '/m2m_' Subject '/Skin.surf.gii ' OutDir...
'/Optimize/CoilCenter_OnTarget.shape.gii ' num2str(Sigma) ' ' OutDir '/Optimize/CoilCenter_OnTarget_s' num2str(Sigma) '.shape.gii -fix-zeros']);
G = gifti([OutDir '/Optimize/CoilCenter_OnTarget_s' num2str(Sigma) '.shape.gii']); % read in the smoothed file;

% read in the skin distance matrix
DistanceMatrix = smartload([HeadModelDir '/m2m_'...
Subject '/SkinDistanceMatrix.mat']);

% preallocate the overall quality distance weighted score;
DistanceWeightedScore = zeros(length(SearchGridVertices),1);

% sweep the search grid vertices;
for i = 1:length(SearchGridVertices)
    DistanceWeightedScore(i) = mean(G.cdata(DistanceMatrix(SearchGridVertices(i),:) <= ErrorTolerance)); % average value score of all vertices within the specified distance of vertex "i" 
end

% save the the overall quality distance weighted score;
save([OutDir '/Optimize/CoilCenter_DistanceWeightedScore_' num2str(ErrorTolerance) 'mm'],...
'DistanceWeightedScore');

% find the coil placement that has the best quality score (on avg.)
% across vertices within the specified distance (5 mm by default);
Idx = find(DistanceWeightedScore==max(DistanceWeightedScore )); 
CoilCenterVertex = SearchGridVertices(Idx(1)); % this is the final coil placement site;
CoilCenterCoords = SKIN.vertices(CoilCenterVertex,:);

% genereate an inverse transform (if needed);
if ~exist([Subdir '/anat/T1w/xfms/acpc2orig.mat'],'file')
system(['convert_xfm -omat ' Subdir '/anat/T1w/xfms/acpc2orig.mat -inverse ' Subdir '/anat/T1w/xfms/acpc.mat']);
end

% write out best coil placement in acpc & native imgage space;
system(['echo ' num2str(CoilCenterCoords(1)) ' ' num2str(CoilCenterCoords(2)) ' ' num2str(CoilCenterCoords(3)) ' > ' OutDir '/Optimize/CoilCenterACPC.txt']);
system(['img2imgcoord -src ' Subdir '/anat/T1w/T1w_acpc.nii.gz -dest ' Subdir '/anat/T1w/T1w.nii.gz -xfm ' Subdir '/anat/T1w/xfms/acpc2orig.mat -mm ' OutDir '/Optimize/CoilCenterACPC.txt > ' OutDir '/Optimize/CoilCenterNative.txt']);

% generate taarget foci (for visualization purposes);
system(['echo Target > ' OutDir '/Optimize/tmp.txt']);
system(['echo 1 0 0 ' num2str(CoilCenterCoords(1)) ' ' num2str(CoilCenterCoords(2)) ' ' num2str(CoilCenterCoords(3)) ' >> ' OutDir '/Optimize/tmp.txt']);
system(['wb_command -foci-create  ' OutDir '/Optimize/CoilCenter.foci -class CoilCenter ' OutDir '/Optimize/tmp.txt ' HeadModelDir '/m2m_' Subject '/Skin.surf.gii']);
system(['rm ' OutDir '/Optimize/tmp.txt']); % remove intermediate file;

%% fine-tune the coil orientation

% Initialize a session
s = sim_struct('SESSION');

% Name of head mesh
s.fnamehead = [HeadModelDir...
'/' Subject '.msh'];

% Output folder
s.pathfem = [OutDir '/Optimize/Simulation/'];

% Initialize a list of TMS simulations
s.poslist{1} = sim_struct('TMSLIST');

% Select coil
s.poslist{1}.fnamecoil = CoilModel;

% specify coil positioning
s.poslist{1}.pos(1).centre = CoilCenterCoords;

% generate an approximate circle around the center position;
D = pdist2(SKIN.vertices,CoilCenterCoords);
A = find(D < 19); % inner diameter;
B = find(D < 20); % outer diameter;

% sort coordinates in a radial fashion (this time with no subsampling);
[RefDirs] = SortCircleCoords(SKIN.vertices(B(~ismember(B,A)),:)); 

% preallocate;
RefDirsVertices = ...
zeros(size(RefDirs,1),1);

% sweep a range of
% coil orientations;
for i = 1:length(RefDirs)
    
    % specify & save coil position;
    s.poslist{1}.pos(i).centre = CoilCenterCoords;
    s.poslist{1}.pos(i).pos_ydir = [RefDirs(i,1), RefDirs(i,2), RefDirs(i,3)];
    
    % while we are at it, lets log 
    % the corresponding skin vertex numbers;
    Tmp = pdist2(SKIN.vertices,RefDirs(i,:));
    Idx = find(Tmp==min(Tmp));
    RefDirsVertices(i) = Idx(1);
    
end
    
% write to volume;
s.map_to_vol = true;
s.fields = 'e'; % normE only;

% remove the dir. if it exists;
if exist([OutDir '/Optimize/Simulation/'],'dir')
system(['rm -rf ' OutDir '/Optimize/Simulation/']);
end

%run simulation;
run_simnibs(s);

% map concatenated volume to the 32k surface;
system(['fslmerge -t ' OutDir '/Optimize/Simulation/subject_volumes/normE.nii.gz ' OutDir '/Optimize/Simulation/subject_volumes/' Subject '*_normE.nii.gz']);
system(['rm ' OutDir '/Optimize/Simulation/subject_volumes/' Subject '*_normE.nii.gz']); % remove intermediate files;
system(['wb_command -volume-to-surface-mapping ' OutDir '/Optimize/Simulation/subject_volumes/normE.nii.gz  ' MIDTHICK_32k{1} ' ' OutDir '/Optimize/Simulation/subject_volumes/normE.L.32k_fs_LR.shape.gii -ribbon-constrained ' WHITE_32k{1} ' ' PIAL_32k{1} ' -interpolate ENCLOSING_VOXEL']);
system(['wb_command -volume-to-surface-mapping ' OutDir '/Optimize/Simulation/subject_volumes/normE.nii.gz  ' MIDTHICK_32k{2} ' ' OutDir '/Optimize/Simulation/subject_volumes/normE.R.32k_fs_LR.shape.gii -ribbon-constrained ' WHITE_32k{2} ' ' PIAL_32k{2} ' -interpolate ENCLOSING_VOXEL']);
system(['wb_command -metric-mask ' OutDir '/Optimize/Simulation/subject_volumes/normE.L.32k_fs_LR.shape.gii ' ROI_32k{1} ' ' OutDir '/Optimize/Simulation/subject_volumes/normE.L.32k_fs_LR.shape.gii']);
system(['wb_command -metric-mask ' OutDir '/Optimize/Simulation/subject_volumes/normE.R.32k_fs_LR.shape.gii ' ROI_32k{2} ' ' OutDir '/Optimize/Simulation/subject_volumes/normE.R.32k_fs_LR.shape.gii']);
system(['wb_command -cifti-create-dense-timeseries ' OutDir '/Optimize/Simulation/subject_volumes/normE.dtseries.nii -left-metric ' OutDir '/Optimize/Simulation/subject_volumes/normE.L.32k_fs_LR.shape.gii -roi-left ' ROI_32k{1} ' -right-metric ' OutDir '/Optimize/Simulation/subject_volumes/normE.R.32k_fs_LR.shape.gii -roi-right ' ROI_32k{2}]);
system(['rm ' OutDir '/Optimize/Simulation/subject_volumes/*shape*']);

% rename the cifti file and remove some intermediate files;
system(['mv ' OutDir '/Optimize/Simulation/subject_volumes/normE.dtseries.nii '...
OutDir '/Optimize/normE_BestCoilCenter+AllOrientations.dtseries.nii']);
system(['rm -rf ' OutDir '/Optimize/Simulation/']);

% read the cifti file & count how many orientations were attempted
NormE = ft_read_cifti_mod([OutDir '/Optimize/normE_BestCoilCenter+AllOrientations.dtseries.nii']);
nCols = size(NormE.data,2);

% preallocate the two main variables;
OnTarget = zeros(1,nCols,length(Thresholds)); % "OnTaget" variable (% of E-field that falls in the ROI);

% sweep the coil orientations;
for i = 1:size(NormE.data,2)
    
    % sweep all of the thresholds;
    for ii = 1:length(Thresholds)

        HotSpot = NormE.data(1:59412,i) > prctile(NormE.data(1:59412,i),Thresholds(ii)); % this is the hotspot
        OnTarget(1,i,ii) = sum(VA.data(HotSpot & Target==1)) / sum(VA.data(HotSpot));

    end
    
end

% clear
% variable
clear NormE

% save some variables;
save([OutDir '/Optimize/CoilOrientation_OnTarget'],'OnTarget');

% average accross the e-field thresholds;
AvgOnTarget = mean(OnTarget,3); % on-target;

% read in the template metric file;
G = gifti([OutDir '/Optimize/CoilCenter_OnTarget.shape.gii']);
G.cdata = zeros(size(G.cdata)); % blank slate;

% quality criteria (% of hotspot on target);
G.cdata(RefDirsVertices) = AvgOnTarget; % average across orientations, for now.
save(G,[OutDir '/Optimize/CoilOrientation_OnTarget.shape.gii']); % write out the on-target metric file;
system(['wb_command -metric-dilate ' OutDir '/Optimize/CoilOrientation_OnTarget.shape.gii ' HeadModelDir '/m2m_' Subject '/Skin.surf.gii 2  ' OutDir '/Optimize/CoilOrientation_OnTarget.shape.gii -nearest']);
system(['wb_command -metric-smoothing ' HeadModelDir '/m2m_' Subject '/Skin.surf.gii ' OutDir '/Optimize/CoilOrientation_OnTarget.shape.gii ' num2str(Sigma) ' ' OutDir '/Optimize/CoilOrientation_OnTarget_s' num2str(Sigma) '.shape.gii -fix-zeros']);

% find the coil orientation that has
% the best quality score (on average);
Idx = find(AvgOnTarget==max(AvgOnTarget));
OrientationVertex = RefDirsVertices(Idx(1)); % this is the final coil placement site;
CoilOrientationCoords = SKIN.vertices(OrientationVertex,:);

% write out best coil placement in acpc & native imgage space;
system(['echo ' num2str(CoilOrientationCoords (1)) ' ' num2str(CoilOrientationCoords (2)) ' ' num2str(CoilOrientationCoords (3)) ' > ' OutDir '/Optimize/CoilOrientationACPC.txt']);
system(['img2imgcoord -src ' Subdir '/anat/T1w/T1w_acpc.nii.gz -dest ' Subdir '/anat/T1w/T1w.nii.gz -xfm ' Subdir '/anat/T1w/xfms/acpc2orig.mat -mm ' OutDir '/Optimize/CoilOrientationACPC.txt > ' OutDir '/Optimize/CoilOrientationNative.txt']);

% generate the reference 
% orientation foci (for visualization purposes);
system(['echo Target > ' OutDir '/Optimize/tmp.txt']);
system(['echo 1 0 0 ' num2str(CoilOrientationCoords (1)) ' ' num2str(CoilOrientationCoords (2)) ' ' num2str(CoilOrientationCoords (3)) ' >> ' OutDir '/Optimize/tmp.txt']);
system(['wb_command -foci-create  ' OutDir '/Optimize/CoilOrientation.foci -class CoilOrientation ' OutDir '/Optimize/tmp.txt ' HeadModelDir '/m2m_' Subject '/Skin.surf.gii']);
system(['rm ' OutDir '/Optimize/tmp.txt']); % remove intermediate file;

% write out the final E-field map
NormE = ft_read_cifti_mod([OutDir '/Optimize/normE_BestCoilCenter+AllOrientations.dtseries.nii']); NormE.data = NormE.data(:,Idx(1));
ft_write_cifti_mod([OutDir '/Optimize/normE_BestCoilCenter+BestOrientation.dtseries.nii'],NormE);

end

function [Output] = SortCircleCoords(Coords)
% cjl;

% preallocate;
Output = zeros(size(Coords));

% preallocate;
Used = [];
Idx = 1;

% sweep the coordinates;
for i = 1:size(Coords,1)
    D = pdist2(Coords(Idx,:),Coords);
    D(Used)=nan;
    Idx = find(D==min(nonzeros(D)));
    Idx = Idx(1); % in case there is more than one;
    Output(i,:) = Coords(Idx,:);
    Used = [Used Idx];
end

end

% 
function out = smartload(matfile)

out = load(matfile);
names = fieldnames(out);
out = eval(['out.' names{1}]);

end